export type MeaningEntry = { text: string; url: string };

export const karma_meaning: Record<number, MeaningEntry> = {
  1: { text: 'Лидерский импульс — личная стратегия и смелые шаги', url: 'https://t.me/JyotishGPT/57?src=bot' },
  2: { text: 'Синергия и союзы — сила диалога и надёжных партнёров', url: 'https://t.me/JyotishGPT/59?src=bot' },
  3: { text: 'Творчество и коммуникация — видимость ускоряет рост', url: 'https://t.me/JyotishGPT/61?src=bot' },
  4: { text: 'Система и устойчивость — дисциплина даёт прорыв', url: 'https://t.me/JyotishGPT/63?src=bot' },
  5: { text: 'Перемены и свобода — время для экспериментов', url: 'https://t.me/JyotishGPT/65?src=bot' },
  6: { text: 'Ответственность и сервис — качество и забота', url: 'https://t.me/JyotishGPT/67?src=bot' },
  7: { text: 'Глубина и аналитика — сила ума и концентрации', url: 'https://t.me/JyotishGPT/69?src=bot' },
  8: { text: 'Амбиция и результат — про деньги и влияние', url: 'https://t.me/JyotishGPT/72?src=bot' },
  9: { text: 'Смысл и масштаб — проекты на благо других', url: 'https://t.me/JyotishGPT/74?src=bot' },
};
export const ahamkara_meaning: Record<number, MeaningEntry> = {1:{text:'Сила личности и лидерство',url:'https://t.me/JyotishGPT/206?src=bot'},2:{text:'Чувствительность и гармония',url:'https://t.me/JyotishGPT/209?src=bot'},3:{text:'Лёгкость общения и радость жизни',url:'https://t.me/JyotishGPT/214?src=bot'},4:{text:'Практичность и упорство',url:'https://t.me/JyotishGPT/216?src=bot'},5:{text:'Жажда приключений и опыта',url:'https://t.me/JyotishGPT/219?src=bot'},6:{text:'Любовь и умение создавать уют',url:'https://t.me/JyotishGPT/221?src=bot'},7:{text:'Аналитический ум и поиск знаний',url:'https://t.me/JyotishGPT/223?src=bot'},8:{text:'Уверенность и материальные достижения',url:'https://t.me/JyotishGPT/226?src=bot'},9:{text:'Сострадание и стремление к высшему',url:'https://t.me/JyotishGPT/228?src=bot'}};
export const dharma_meaning: Record<number, MeaningEntry> = {1:{text:'Миссия вести за собой и быть примером',url:'https://t.me/JyotishGPT/265?src=bot'},2:{text:'Путь посредника и создателя гармонии',url:'https://t.me/JyotishGPT/267?src=bot'},3:{text:'Раскрытие себя через творчество и радость',url:'https://t.me/JyotishGPT/266?src=bot'},4:{text:'Долг строителя и хранителя порядка',url:'https://t.me/JyotishGPT/268?src=bot'},5:{text:'Миссия перемен и открытия новых дорог',url:'https://t.me/JyotishGPT/269?src=bot'},6:{text:'Забота о близких и поддержка общества',url:'https://t.me/JyotishGPT/270?src=bot'},7:{text:'Учитель и исследователь глубин',url:'https://t.me/JyotishGPT/271?src=bot'},8:{text:'Воплощение амбиций в результат',url:'https://t.me/JyotishGPT/272?src=bot'},9:{text:'Служение людям и передача опыта',url:'https://t.me/JyotishGPT/273?src=bot'}};
export const expression_meaning: Record<number, MeaningEntry> = {1:{text:'Смелость и решительность в проявлении',url:'https://t.me/JyotishGPT/85?src=bot'},2:{text:'Умение слышать других и сохранять баланс',url:'https://t.me/JyotishGPT/86?src=bot'},3:{text:'Творческая лёгкость и радость жизни',url:'https://t.me/JyotishGPT/87?src=bot'},4:{text:'Стабильность и чёткая форма самовыражения',url:'https://t.me/JyotishGPT/88?src=bot'},5:{text:'Движение, свобода и авантюра',url:'https://t.me/JyotishGPT/89?src=bot'},6:{text:'Красота, забота и гармония',url:'https://t.me/JyotishGPT/90?src=bot'},7:{text:'Мудрость и глубина в словах',url:'https://t.me/JyotishGPT/91?src=bot'},8:{text:'Сила воли и масштабность замыслов',url:'https://t.me/JyotishGPT/92?src=bot'},9:{text:'Щедрость духа и вдохновение для других',url:'https://t.me/JyotishGPT/93?src=bot'}};
export const vyavadhana_meaning: Record<number, MeaningEntry> = {1:{text:'Есть ощущение, что всё приходится делать самому. Но именно это даёт силу и уверенность.',url:'https://t.me/BAPHbl'},2:{text:'Бывают ситуации выбора и баланса; именно здесь рождается внутренняя гармония.',url:'https://t.me/BAPHbl'},3:{text:'Проверки радостью и общением: Вселенная учит выражать себя свободно.',url:'https://t.me/BAPHbl'},4:{text:'Урок порядка и терпения; так строится фундамент будущего.',url:'https://t.me/BAPHbl'},5:{text:'Перемены и внезапные повороты выбивают из колеи, но дарят свободу.',url:'https://t.me/BAPHbl'},6:{text:'Уроки через отношения, любовь и принятие.',url:'https://t.me/BAPHbl'},7:{text:'Проверки через одиночество и поиск смысла дают сильнейший рост.',url:'https://t.me/BAPHbl'},8:{text:'Вызовы через деньги, успех и статус — это часть пути.',url:'https://t.me/BAPHbl'},9:{text:'Число завершения и отдачи: важно отпускать и собирать мудрость.',url:'https://t.me/BAPHbl'}};
